import Head from "next/head";
import Features from "../components/home/Features";
import Gallery from "../components/home/Gallery";
// import Image from "next/image";
import Hero from "../components/home/Hero";
import Layout from "../components/Layout";
import Reviews from "../components/home/Reviews";

export default function Home() {
  return (
    <div className="text-amber-900 max-w-7xl flex mx-auto">
      <Head>
        <title>horizon app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Hero />
        <Features />
        <Gallery />
        <Reviews />
      </Layout>
    </div>
  );
}
